name: check for mypy updates
on: 
  pull_request:
    branches:    
      - master
  push:
    branches:
      - master
jobs:
  tests:
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install deps
        run: |
          pip install ".[dev]"
          mypy --install-types
      - name: MyPy
        run: mypy envrun
      - name: Black
        run: black envrun --check
